CREATE TABLE `webstories`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`));

CREATE TABLE `webstories`.`story` (
`storyId` INT NOT NULL AUTO_INCREMENT,
`userId` INT NOT NULL,
`category` VARCHAR(45) NOT NULL,
`title` VARCHAR(45) NOT NULL,
`summary` Text ,
`storyContent` TEXT NOT NULL,
`storyViews` INT DEFAULT 0,
`downloads` INT DEFAULT 0,
  PRIMARY KEY (`storyId`));

CREATE TABLE `webstories`.`story_views`(
`storyId` INT NOT NULL,
`userViewed` INT DEFAULT 0, 
`viewTimeStamp` DATE DEFAULT 0
);

CREATE TABLE `webstories`.`story_downloads`(
`storyId` INT NOT NULL,
`user` INT DEFAULT 0, 
`download_TimeStamp` DATE DEFAULT 0
);

insert into users values(1,'Danial','Danial','Danial@gmail.com');
insert into users values(2,'Oksana','Oksana','Oksana@gmail.com');
insert into users values(3,'Motya','Motya','Motya@gmail.com');
insert into users values(4,'Merry','Merry','Merry@gmail.com');

insert into story values(1,1,'Moral','The fox and the grapes','When writing a summary, remember that it should be in the form of a paragraph. A summary begins with an introductory sentence that states the texts title, author and main point of the text as you see it. A summary is written in your own words. A summary contains only the ideas of the original text.','One day, a fox became very hungry as he went to search for some food. He searched high and low, but couldn’t find something that he could eat.
Finally, as his stomach rumbled, he stumbled upon a farmer’s wall. At the top of the wall, he saw the biggest, juiciest grapes he’d ever seen. They had a rich, purple color, telling the fox they were ready to be eaten.To reach the grapes, the fox had to jump high in the air. As he jumped, he opened his mouth to catch the grapes, but he missed. The fox tried again but missed yet again.
He tried a few more times but kept failing.Finally, the fox decided it was time to give up and go home. While he walked away, he muttered, “I’m sure the grapes were sour anyway.”', 0,0);
insert into story values(2,3,'Moral', 'The Ants and thre Grasshoper','One bright autumn day, a family of ants was busy working in the warm sunshine. They were drying out the grain they had stored up during the summer when a starving grasshopper came up. With his fiddle under his arm, the grasshopper humbly begged for a bite to eat.“What!” cried the ants, “Haven’t you stored any food away for the winter? What in the world were you doing all summer?”“I didn’t have time to store any food before winter,” the grasshopper whined. “I was too busy making music that the summer flew by.”The ants simply shrugged their shoulders and said, “Making music, were you? Very well, now dance!” The ants then turned their backs on the grasshopper and returned to work.', 0,0);
insert into story values(3,3,'Moral', 'The Proud Rose','Once upon a time, in a desert far away, there was a rose who was so proud of her beautiful looks. Her only complaint was growing next to an ugly cactus. Every day, the beautiful rose would insult and mock the cactus on his looks, all while the cactus remained quiet. All the other plants nearby tried to make the rose see sense, but she was too swayed by her own looks.One scorching summer, the desert became dry, and there was no water left for the plants. The rose quickly began to wilt. Her beautiful petals dried up, losing their lush color.Looking to the cactus, she saw a sparrow dip his beak into the cactus to drink some water. Though ashamed, the rose asked the cactus if she could have some water. The kind cactus readily agreed, helping them both through the tough summer, as friends.', 0,0);
insert into story values(4,1,'Horror', 'Title four-horror story','When writing a summary, remember that it should be in the form of a paragraph. A summary begins with an introductory sentence that states the texts title, author and main point of the text as you see it. A summary is written in your own words. A summary contains only the ideas of the original text.','‘The Gift of the Magi’ is an American writer ‘O. Henry’, which become one of the famous Christmas stories for Children. Henry ‘, first published in 1905. This story is about a young couple, Jim and Della, poor but very loving. It’s Christmas time and Della wants to buy a nice Christmas present for her husband – however, she has very little money. One of Della’s treasured assets is her beautiful layered hair – but since she didn’t have enough savings to buy Jim’s Christmas presents, she cut and sold her hair for $ 20 and buy it. Perfect gift for Jim. Jim also sells his grandfather’s precious gold pocket watch – something he holds firmly on his lap – to buy a present for her.When he returned home, Jim was dumbfounded when he found Della’s new hairstyle. Della bought a watch strap for Jim’s favorite pocket watch, and he bought precious hair combs for her long hair. When they receive gifts, they realize they are no longer helpful to them. The two sold their precious possessions to make each other happy, showing their love for each other. They sit together for dinner but are not angry. The story ends there, but the narrator compares the gifts Jim and Della gave each other with the gifts of the witches in the Bible. This story is about the personal sacrifices people make to their loved ones.', 0,0);
insert into story values(5,2,'Horror','', 'Title five-Horror story','When writing a summary, remember that it should be in the form of a paragraph. A summary begins with an introductory sentence that states the texts title, author and main point of the text as you see it. A summary is written in your own words. A summary contains only the ideas of the original text.','Some time later,Joseph and Mary had to travel to Bethlehem, a long way from Nazareth. Mary’s babies are about to be born and so they are very slow. When they arrived in Bethlehem, they had no room to live in because all the inns and rooms were occupied. The couple was in the barn, a goat and a horse, and on the very night Jesus was born. Jesus is placed in a manger (feeding place) after birth and wrapped in a cloth.
On the outskirts of Bethlehem, their shepherds saw an angel appear before them. The angel said to them: “Your messiah was born in Bethlehem today. He is lying in the manger ”. When the shepherds ran back to find Joseph, Mary, and Jesus in the barn, they were surprised and happy.At the time of Jesus’ birth, a new bright star appeared in the sky. There were three wise men in a distant country who knew that Jesus’ appearance was a sign of the arrival of a great king and they rushed to find him. King Herod heard that the wise men were looking for the great new king, whom he knew would replace him. King Herod planned to kill the baby, but no one knew about it yet.', 0,0);
insert into story values(6,1,'thriller', 'Title one','When writing a summary, remember that it should be in the form of a paragraph. A summary begins with an introductory sentence that states the texts title, author and main point of the text as you see it. A summary is written in your own words. A summary contains only the ideas of the original text.','Christmas is the perfect occasion to tell the story of Jesus’ birth. This is the story. A young woman named Mary lives in a town called Nazareth and is engaged to a man named Joseph. One night, God sent an angel named Gabriel to visit Mary. The angel told Mary: “God is very pleased with you and you will soon become pregnant and have a baby boy. Name him Jesus because he will be God’s own son. “Mary is scared but believes in God and believes everything will be fine. The angel tells Mary to live with her cousin Elizabeth and her husband Zachariah as they will soon become the parents of a child that will pave the way for Jesus Mary lived with her cousin for three months and then returned to Nazareth.', 0,0);
insert into story values(7,3,'Fiction', 'Soafia Princess','This story is about Sofia princess','Meet Sofia, a little girl who lives a rather ordinary life. But everything changes when her mother, Miranda, marries the king. Overnight, Sofia becomes a princess, moves into the castle, gains a step-brother, a step-sister...and the ability to talk to her new animal friends thanks to a magical amulet! Now, life is anything but ordinary for Sofia the First! This read-along storybook features real character voices from the hit television movie and series "Sofia the First!"', 0,0);
insert into story values (8,2,'thriller', 'Title two','When writing a summary, remember that it should be in the form of a paragraph. A summary begins with an introductory sentence that states the texts title, author and main point of the text as you see it. A summary is written in your own words. A summary contains only the ideas of the original text.','Some time later, Joseph and Mary had to travel to Bethlehem, a long way from Nazareth. Mary’s babies are about to be born and so they are very slow. When they arrived in Bethlehem, they had no room to live in because all the inns and rooms were occupied. The couple was in the barn, a goat and a horse, and on the very night Jesus was born. Jesus is placed in a manger (feeding place) after birth and wrapped in a cloth.
On the outskirts of Bethlehem, their shepherds saw an angel appear before them. The angel said to them: “Your messiah was born in Bethlehem today. He is lying in the manger ”. When the shepherds ran back to find Joseph, Mary, and Jesus in the barn, they were surprised and happy.At the time of Jesus’ birth, a new bright star appeared in the sky. There were three wise men in a distant country who knew that Jesus’ appearance was a sign of the arrival of a great king and they rushed to find him. King Herod heard that the wise men were looking for the great new king, whom he knew would replace him. King Herod planned to kill the baby, but no one knew about it yet.', 0,0);
insert into story values(9,3,'thriller', 'Title three','This story is about a boy who lives with his father and mother. He’s kind and obedient and shares all of his toys with his friends. However, he made a mistake: he always forgot to do odd jobs and other important jobs he was asked to do. Every time he is asked to do something and then asked, he has an answer, “I forgot.” If he was sent to the tailor to remind him of an urgent change, he would forget to tell the tailor about it. If he were given money to pay for electricity, his mother would find the money and bills in his pocket that very night. The reason for not doing a specific job remains the same. You guessed it right – “I forgot.”
Parents worry that this forgetful habit will affect the boy’s adult life, making it difficult for him. They decide to do something about it to make him remember everything. Christmas is coming, and like the other children, the boy is busy preparing the bill for Santa Claus, asking for his favorite items. His mother said, “Santa might forget to bring those for you.” But the boy is sure that Santa Claus will look like he will put them in his socks so he will leave the list.
On Christmas morning, he woke up early and hurriedly checked his socks, pretty sure Santa would deliver all he wanted. His mother knew what was going to happen and stayed away from him. The boy stood in front of his mother with a long list of all the jobs he had been asked to do during the past year. At the bottom of the list, bold text is written, “I FORGET”.', 0,0);
insert into story values(10,3,'Funny', 'The Spotty Grey Kitten',,'This story is about little kitten -Grady','Grady was a little, grey kitten. He had a white spot on his back and a black spot on his nose. Grady lived with his mum and two sisters on a farm.Grady’s sisters were white with black spots. Both of his sisters were very good. Grady was the naughty one. He was always getting into trouble.
Grady was very adventurous. He wanted to explore the farm. One day he went out into the farmyard to see what was in the big wide world.Grady said to himself, “I am not afraid of anything!”Suddenly a big monster roared out of the garage and sent Grady spinning into the bushes. He did not know what had roared past. He picked himself up and decided it was time to go home.Grady looked left and he looked right, but there was nowhere that looked like home. He was lost.‘Oh dear,’ Grady thought. ‘Now what shall I do?’ He walked across a field and suddenly he stopped!There in front of him was a furry, white animal with spots on its back. Grady thought it must be one of his sisters.Grady ran up to the furry, spotted animal.“Can you take me home?” asked Grady.“No,” said the furry animal. “You do not belong in my home.“Look at you, you do not have big ears and you do not hop like me,” said the furry animal.', 0,0);

